name: build

on:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build sccache
        run: |
          cargo install sccache --version $(echo ${{ github.ref }} | awk -F'/' '{ print $3 }') --features="s3 redis gcs memcached azure" --target=x86_64-unknown-linux-gnu
          cp -v /home/runner/.cargo/bin/sccache .
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: sccache
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
